baseurl: "https://covid19-data-forum.org"
title: "COVID-19 Data Forum"
canonifyurls: true
theme: "covid19-data-forum"
publishDir: public

GoogleAnalytics: "UA-165738921-1"

params:
  # Conference info
  Name: "COVID-19"
  Subname: "Data Forum"
  Description: "COVID-19 Data Forum: A series of multidisciplinary, online meetings for topic experts to focus on data-related aspects of the scientific response to the pandemic."
  Date: "Upcoming event: Making COVID-19 clinical data available and useful - Aug 13, 2020 - 9am PDT"
  Price: "" # If your event is free, just comment this line
  Venue: "Virtual Online"
  Address: ""
  City:  "Virtual"
  State: "Online"
  Images: ["/img/cover.png"]
  GoogleMapsKey: "my-secret-maps-key"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    #- promo
    - about
    - events
    - committee
    - sponsors
    #- schedule
    #- speakers
    #- agenda
    #- location
    #- schedule
    #- partners
    #- contact

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    events: "Events"
    committee: "Organizing Committee"
    sponsors: "Sponsors"
    #promo: "Promo"
    #contact: "Contact"
    #speakers: "Speakers"
    #location: "Location"
    #agenda: "Agenda"
    #events: "Events"
    #schedule: "Schedule"
    #partners: "Partners"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Register now!"
    link: "https://stanford.zoom.us/webinar/register/WN_50bLGIAWS6qNjrwPFUpyvA"
  #  text: "More Information"
  #  link: "mailto:covid-19-data-forum@r-consortium.org"
>>>>>>> 897d60be995797806c379ef6f2e2fba54c8e8240


  # Promo box items
  Promo:
    - text: >
        This is a promotion »
      actionURL: "https://r-consortium.org/"

  # Upcoming Events
  UpcomingEvents:
    - title: "Beyond case counts: Making COVID-19 clinical data available and useful"
      date: "August 13, 2020"
      time: "9:00 AM San Francisco | 16:00 UTC"
      description: >
        COVID-19 is the first pandemic to occur in the age of open data. Public health agencies
        around the world are releasing case counts to the public, and scientists are providing
        analyses and forecasts in real-time. However, the content of this data has so far been
        limited to simple metrics like cases, deaths, and hospitalizations at coarse geographic and
        demographic scales. To drive the next-phase of COVID-19, scientists need access to
        higher-dimensional patient-level data, so we can understand how the virus causes disease,
        why are some more at risk than others, when and how is transmission occurring, what
        therapeutics are more likely to work, and what healthcare resources are being used. But
        sharing such data brings up tremendous challenges in terms of patient privacy and data
        standardization. The COVID-19 Data Forum, a collaboration between Stanford University and
        the R Consortium, is hosting the event "Beyond case counts: Making COVID-19 clinical data
        available and useful" to push the conversation forward on these issues. The event will
        include talks by representatives from international collaborative teams who are working to
        collect and share detailed clinical and biological data from individuals with COVID-19.  The
        event will be open to the public, and is part of a continuing series focusing on
        data-related aspects of the scientific response to the pandemic.
      agenda:
        - talk: ""
          speakerName: "Jenna Reps"
          speakerURL: "https://www.ohdsi.org/who-we-are/collaborators/jenna-reps/"
          affiliations:
            - title: "Affiliate"
              organizationName: "OHDSI consortium's patient-level prediction working group"
              organizationURL: "https://www.ohdsi.org"
            - title: "Member"
              organizationName: "Jaansen R&D"
              organizationURL: "https://www.jnj.com/tag/janssen-research-development"
        - talk: ""
          speakerName: "Andrea Ganna"
          speakerURL: "http://www.atgu.mgh.harvard.edu/people/andrea-ganna/"
          affiliations:
            - title: "Affiliate"
              organizationName: "COVID-19 Host Genetics Initiative"
              organizationURL: "https://www.ohdsi.org"
            - title: "Group Leader"
              organizationName: "Genetic Epidemiology Lab"
              organizationURL: "https://www.dsgelab.org/"
        - talk: ""
          speakerName: "Ken Massey"
          speakerURL: ""
          affiliations:
            - title: "Affiliate"
              organizationName: "EndPandemic National Data Consortium"
              organizationURL: "https://endpandemic.org"
            - title: "Chief Life Sciences Officer"
              organizationName: "Saama Technologies"
              organizationURL: "https://www.saama.com"
        - talk: ""
          speakerName: "Ryan Tibshirani"
          speakerURL: "https://www.stat.cmu.edu/~ryantibs/"
          affiliations:
            - title: "Lead Researcher"
              organizationName: "Delphi Covid-19 Response Team"
              organizationURL: "https://delphi.cmu.edu"
            - title: "Associate Professor"
              organizationName: "Department of Statistics, Carnegie Mellon University"
              organizationURL: "https://www.stat.cmu.edu"
              
#      sponsor: https://sponsor

  # Past Events
  PastEvents:
    - title: "Introducing the COVID-19 Data Forum"
      date: "Thursday, May 14, 2020"
      time: "19:00 UTC | 12pm PDT | 3pm EDT | 8pm London | 9pm Paris | 3am Beijing"
#      register: https://register
#      sponsor: https://sponsor
      description: |
        The opening event of the COVID-19 Data Forum was held on May 14 2020 and attracted several
        hundred attendees for a lively discussion of the current state of COVID-19 data and the
        challenges researchers face.
      agenda:
        - talk: "Welcome and opening remarks"
          speakerName: "Joseph Rickert"
          speakerURL: "https://rstudio.com/speakers/joseph-rickert/"
          affiliations:
            - title: "Chair R Consortium Board of Directors"
              organizationName: "R Consortium"
              organizationURL: "https://r-consortium.org"
          replay: "https://www.youtube.com/watch?v=6N1p99bLXjk"
        - talk: "Modeling COVID-19 Spread and Control: Data Needs and Challenges"
          speakerName: "Alison Hill"
          speakerURL: "https://ped.fas.harvard.edu/people/alison-hill"
          affiliations:
            - title: "John Harvard Distinguished Science Fellow"
              organizationName: "Harvard's Program for Evolutionary Dynamics"
              organizationURL: "https://ped.fas.harvard.edu/"
          replay: "https://youtu.be/6N1p99bLXjk?t=287"
        - talk: "Collecting and Visualizing COVID-19 Case Count Data from Multiple Open Sources"
          speakerName: "Ryan Hafen"
          speakerURL: "https://ryanhafen.com/"
          affiliations:
            - title: "Data scientist consultant"
              organizationName: "Preva Group"
              organizationURL: "https://www.prevagroup.com/"
            - title: "Adjunct Assistant Professor"
              organizationName: "Purdue University"
              organizationURL: "https://www.purdue.edu/"
          replay: "https://youtu.be/6N1p99bLXjk?t=1249"
        - talk: "Spatial and Space-Time Data on COVID-19"
          speakerName: "Orhun Aydin"
          speakerURL: "https://www.linkedin.com/in/orhunaydin/"
          affiliations:
            - title: "Researcher and Product Engineer"
              organizationName: "ESRI"
              organizationURL: "https://www.esri.com/en-us/home"
            - title: "Lecturer"
              organizationName: "University of Southern California"
              organizationURL: "https://spatial.usc.edu/team-view/orhun-aydin/"
          replay: "https://youtu.be/6N1p99bLXjk?t=2297"
        - talk: "Data in the COVID-19 Pandemic"
          speakerName: "Noam Ross"
          speakerURL: "https://www.ecohealthalliance.org/personnel/dr-noam-ross"
          affiliations:
            - title: "Senior Research Scientist"
              organizationName: "EcoHealth Alliance"
              organizationURL: "https://www.ecohealthalliance.org/"
          replay: "https://youtu.be/6N1p99bLXjk?t=3323"

  # List of Committee members
  Committee:
    - name: "Joseph Rickert"
      jobtitle: "Chair R Consortium Board of Directors"
      url: "https://www.r-consortium.org"
    - name: "John Chambers"
      jobtitle: "Stanford Department of Statistics and Stanford Data Science"
      url: "https://web.stanford.edu/~jmc4"
    - name: "Michael Kane"
      jobtitle: "Assistant Professor, Department of Biostatistics, Yale University"
      url: "https://medicine.yale.edu/profile/michael_kane/"
    - name: "Balasubramanian Narasimhan"
      jobtitle: "Senior Research Scientist, Department of Biomedical Data Sciences, Stanford University"
      url: "https://web.stanford.edu/~naras"
    - name: "Chris Mentzel"
      jobtitle: "Executive Director, Stanford Data Science"
      url: "https://datascience.stanford.edu/people/chris-mentzel"
    - name: "Alison Hill"
      jobtitle: "John Harvard Distinguished Science Fellow, Harvard University"
      url: "https://www.people.fas.harvard.edu/~alhill/"

  # List of Sponsors
  Sponsors:
    - name: "R Consortium"
      logo: "/img/RConsortium_Horizontal_Pantone.svg"
      url: "https://www.r-consortium.org"
    - name: "Stanford Data Science Institute"
      logo: "/img/stanford_data_science_institute.png"
      url: "https://datascience.stanford.edu/"

## The following config options are unused.

  # List of Partners
  Partners:
    - name: "Hugo"
      logo: "/img/hugo.jpg"
      url: "https://gohugo.io"
    - name: "BrazilJS"
      logo: "/img/partner.png"
      url: "http://braziljs.org"

  #speakers
  Speakers:
    - name: "Orhun Aydin"
      photo: "https://spe.org/media/filer_public_thumbnails/filer_public/71/67/716717e4-e7ba-4ab3-8eb6-a4dfd930fec5/orhun-aydin.jpg__205x192_q85_subsampling-2.jpg"
      bio: "Senior Researcher at ESRI and Lecturer at USC"
      company: "ESRI"
      link:
        href: "https://spatial.usc.edu/team-view/orhun-aydin/"
        text: "Website"
    - name: "Ryan Hafen"
      photo: "https://ryanhafen.com/img/hafen3.jpg"
      bio: "Data scientist consultant with Preva Group, and adjunct assistant professor, Purdue University"
      company: "Purdue University"
      link:
        href: "https://ryanhafen.com/"
        text: "Website"
    - name: "Alison L. Hill"
      photo: "https://www.people.fas.harvard.edu/~alhill/images/alison.jpg"
      bio: "Research Fellow and independent principal investigator at Harvard’s Program for Evolutionary Dynamics"
      company: "Harvard - Evolutionary Dynamics"
      link:
        href: "https://www.people.fas.harvard.edu/~alhill/"
        text: "Website"
    - name: "Noam Ross"
      photo: "https://pbs.twimg.com/profile_images/557246848625172481/n7rj_Ee4_400x400.png"
      bio: "Senior Research Scientist, EcoHealth Alliance"
      company: "EcoHealth Alliance"
      link:
        href: "https://www.ecohealthalliance.org/personnel/dr-noam-ross"
        text: "Website"

  # The entire schedule
  Schedule:
    - name: "Linus Torvalds"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: "Linux Foundation"
      link:
        href: "https://twitter.com/linus"
        text: "@linus"
      presentation:
        title: "Digging into a Linux Kernel"
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
        time: "10h00"

    - name: "Bill Gates"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: "Microsoft"
      link:
        href: "https://github.com/billy95"
        text: "@billy95"
      presentation:
        title: "Introducing Windows 12"
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
        time: "11h00"

    - name: "Lunch"
      time: "12h00"

    - name: "Chuck Norris"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: "Delta Command"
      link:
        href: "https://twitter.com/littlechuck"
        text: "@littlechuck"
      presentation:
        title: "How to kill a elephant with one finger"
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
        time: "13h00"

    - name: "Steve Jobs"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: "Apple, Inc."
      link:
        href: "https://github.com/stevie"
        text: "@stevie"
      presentation:
        title: "Presenting iPad"
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
        time: "14h00"

    - name: "Coffee-break"
      time: "15h00"

    - name: "Mark Zuckerberg"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: "Facebook"
      link:
        href: "http://twitter.com/zuck"
        text: "@zuck"
      presentation:
        title: "Revealing Facebook Secrets"
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
        time: "16h00"

    - name: "Steve Wozniak"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: "Apple, Inc."
      link:
        href: "http://twitter.com/woz"
        text: "@woz"
      presentation:
        title: "Why do I prefer Android over iPhone"
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
        time: "17h00"

  # The entire schedule
  Agenda:
    - name: "Opening Remarks"
      time: "5 min"

    - name: "Speakers"
      presentation:
        title: "Five talks, 15-min each"
        description: "Speakers will present virtually online via webinar format"
        time: "75 min"

    - name: "Brief Q/A and Closing"
      presentation:
        title: "10min Q&A"
        description: "The forum will close with a brief Q&A session"
        time: "10 min"

  # The entire schedule
  Workshop:
    - name: "Opening"
      time: "5 min"

    - name: "Breakout Session 1 (facilitated groups of 5-6 people)"
      presentation:
        title: "Breakout Session 1"
        description: "Breakout Session 1 (facilitated groups of 5-6 people)"
        time: "75 min"

    - name: "Report"
      presentation:
        title: "Report Out"
        description: "Plenary"
        time: "10 min"

    - name: "Breakout Session 2 (facilitated groups of 5-6 people)"
      presentation:
        title: "Breakout Session 2"
        description: "Breakout Session 2 (facilitated groups of 5-6 people)"
        time: "75 min"

    - name: "Report"
      presentation:
        title: "Report Out"
        description: "Plenary"
        time: "10 min"

    - name: "Breakout Session 3 (Time Permitting)"
      presentation:
        title: "Breakout Session 3 (Time Permitting)"
        description: "Breakout Session 2 (facilitated groups of 5-6 people)"
        time: "75 min"

    - name: "Report"
      presentation:
        title: "Report Out (Time Permitting)"
        description: "Plenary"
        time: "10 min"

    - name: "Conclusion"
      presentation:
        title: "Conclusion / Next steps"
        description: "Open discussion on Data Forum's next steps"
        time: "10 min"
